/**
 * This software was developed and / or modified by Raytheon Company,
 * pursuant to Contract DG133W-05-CQ-1067 with the US Government.
 * 
 * U.S. EXPORT CONTROLLED TECHNICAL DATA
 * This software product contains export-restricted data whose
 * export/transfer/disclosure is restricted by U.S. law. Dissemination
 * to non-U.S. persons whether in the United States or abroad requires
 * an export license or other authorization.
 * 
 * Contractor Name:        Raytheon Company
 * Contractor Address:     6825 Pine Street, Suite 340
 *                         Mail Stop B8
 *                         Omaha, NE 68106
 *                         402.291.0100
 * 
 * See the AWIPS II Master Rights File ("Master Rights File.pdf") for
 * further licensing information.
 **/

/**
 * Imports the English National Dictionary into the database during initial database load.
 *
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Mar 19, 2015 4291       bkowal     Initial creation.
 **/

INSERT INTO bmh.dictionary (name, language, "national") VALUES ('paul-nat', 'ENGLISH', true);

INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (1, '24Z', '2400Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (2, 'u  s   4 41', 'u.s. 441', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (3, 'i 5 95', 'i-595', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (4, '#:##', '@:@@ o clock', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (5, ' <phoneme alphabet="x-cmu" ph=" JH AA0 N S AH0 N V IH0 L">  </phoneme>', 'johnsonville', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (6, 'saturday.', 'sat.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (7, 'alaska daylight time', 'adt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (8, 'august ##', '(08/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (9, 'this afternoon', '.day one...this afternoon.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (10, 'four  twenty five p em<break strength="none"/>', '425 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (11, ' <phoneme alphabet="x-cmu" ph=" F R AY1 D EY2 ">  </phoneme>', 'friday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (12, 'point', 'pt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (13, 'knots.', 'kt.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (14, ' <phoneme alphabet="x-cmu" ph=" K AE2 R EH0 B IY1 AH0 N ">  </phoneme>', 'caribbean', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (15, ' <phoneme alphabet="x-cmu" ph="  IH1 Z AH0 D OW0 R ">  </phoneme>', 'isidore', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (16, 'plus ##', '+@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (17, 'u s   1', 'u.s. 1', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (18, 'cam peachy', 'campeche', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (19, 'ten ay em', '1000 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (20, 'king junior', 'king jr', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (21, '04Z', '0400Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (22, 'minnesota', 'mn', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (23, 'fifteen <break strength="none"/> ee ', 'fifteen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (24, 'december', 'dec', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (25, 'tammy ammy', 'tamiami', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (26, 'four  twenty p em<break strength="none"/>', '420 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (27, 'florida', 'fl', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (28, 'january', 'jan', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (29, 'four ay em', '400 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (30, 'four  twenty three ay em<break strength="none"/>', '423 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (31, 'u  s 98', 'u.s. 98', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (32, 'november.', 'nov.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (33, 'the nex 24 hours', 'the next 24 hours', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (34, ' <phoneme alphabet="x-cmu" ph=" F AH0 L IY1 SH AH0 ">  </phoneme>', 'felicia', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (35, '20 nautical miles to', '20 nmto', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (36, 'one-eighth', '1/8', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (37, 'southwesterly', 'swly', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (38, 'sixteen <break strength="none"/> ee ', 'sixteen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (39, 'thursday.', 'thu.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (40, '7:00', '7:00 O CLOCK', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (41, ' <phoneme alphabet="x-cmu" ph="  S">  </phoneme>', '''s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (42, 'fourteen<break strength="none"/> ee ', 'fourteen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (43, 'and now the extended forecast', '.and now the extended forecast', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (44, 'seventeen <break strength="none"/> ee ', 'seventeen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (45, '00 hunderd UTC', '0000 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (46, ' <phoneme alphabet="x-cmu" ph=" R EH1 Z ER0 V OW0 R ">  </phoneme>', 'reservoir', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (47, 'pacific', 'pac', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (48, '3 0 5 2 2 9 4 5 2 3', '305-229-4523', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (49, 'one <break strength="none"/> ee ', 'one-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (50, ' <phoneme alphabet="x-cmu" ph=" D AA1 AO1 N ">  </phoneme>', 'dawn', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (51, 'nine  ten p em<break strength="none"/>', '910 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (52, 'eighteen <break strength="none"/> ee ', 'eighteen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (53, 'national weather service', 'NWS TPC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (54, 'road', 'rd', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (55, 'two  fifty two ay em<break strength="none"/>', '2:52 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (56, 'five <break strength="none"/> ee ', 'five-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (57, 'for the rest of today', '.for the remainder of today', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (58, 'one-half', '1/2', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (59, 'monday', '.monday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (60, 'july', 'jul.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (61, ' <phoneme alphabet="x-cmu" ph="  N EH1 K S R AE2  D">  </phoneme>', 'nexrad', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (62, 'slew', 'slough', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (63, 'four  twelve p em<break strength="none"/>', '412 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (64, 'noah', 'noaa', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (65, '##.##  feet', '@@.@@ feet', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (66, 'four  twenty two ay em<break strength="none"/>', '4:22 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (67, 'four  twenty five ay em<break strength="none"/>', '4:25 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (68, ' <phoneme alphabet="x-cmu" ph=" M IH1 N ER0 AH0 L ">  </phoneme>', 'mineral', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (69, 'millibars', 'mb', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (70, 'choppy too  rough', 'choppy to rough', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (71, 'eleven p em', '1100 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (72, 'four  twenty one ay em<break strength="none"/>', '421 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (73, 'kilometers an hour', 'km/hr', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (74, 'tennessee', 'tn', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (75, '11Z', '1100Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (76, 'today', '.day one...today.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (77, '06Z', '0600Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (78, 'scattered <break strength="none"/> frost', 'scattered frost', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (79, ' <phoneme alphabet="x-cmu" ph=" EY1 S AH0 AA0 S ">  </phoneme>', 'asos', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (80, '## degrees below zero', 'b@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (81, 'eastern standard time', 'est', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (82, 'four <break strength="none"/> ee ', 'four-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (83, '1 mile an hour', '1 mph', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (84, 'four  twenty eight ay em<break strength="none"/>', '428 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (85, 'four  twenty one ay em<break strength="none"/>', '4:21 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (86, 'one <break strength="none"/> oh eight ay em', '108 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (87, '10 hundred UTC', '1000 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (88, 'october ##', '(10/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (89, 'nautical miles', 'nm', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (90, '# miles', '@ MI', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (91, 'northeasterly', 'nely', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (92, 'southeast', 'se', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (93, 'four  twenty eight p em<break strength="none"/>', '428 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (94, 'friday.', 'fri.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (95, 'northerly', 'nly', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (96, 'sunny', 'southunny', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (97, '# eighths', '@/8', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (98, ' <phoneme alphabet="x-cmu" ph=" EH1 R P OW0 R T ">  </phoneme>', 'arpt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (99, 'd c', 'dc', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (100, 'maine', 'me', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (101, ' <phoneme alphabet="x-cmu" ph=" AE0 T L AE0 N T IH2 K ">  </phoneme>', 'atlantic', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (102, 'vermont', 'vt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (103, '05Z', '0500Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (104, 'three-quarters', '3/4', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (105, 'U S   27', 'U.S.  27', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (106, 'eight <break strength="none"/> ee ', 'eight-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (107, 'ten <break strength="none"/> ee ', 'ten-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (108, ' <phoneme alphabet="x-cmu" ph=" F EH1 N W IH0 K K">  </phoneme>', 'fenwick', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (109, 'two <break strength="none"/> ee ', 'two-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (110, 'puerto rico', 'pr', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (111, 'four  twenty one p em<break strength="none"/>', '421 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (112, '06 hundred UTC', '0600 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (113, ' <phoneme alphabet="x-cmu" ph=" S IY0 EY0 G OW0    D  EY0">  </phoneme><break strength="none"/> <phoneme alphabet="x-cmu" ph="  AA0 V IY1 L AA0">  </phoneme>', 'CIEGO DE AVILA', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (114, ' <phoneme alphabet="x-cmu" ph=" K R AO1 S R OW0 D Z ">  </phoneme>', 'xrds', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (115, 'tuesday', 'tue', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (116, '#:## p em', '@@@ PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (117, ' <phoneme alphabet="x-cmu" ph=" AA0 N R IY1 K EY0 ">  </phoneme>', 'enrique', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (118, 'per reihn', 'Perrine', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (119, ' <phoneme alphabet="x-cmu" ph=" D EH0 L M AA1 R V AH0 ">  </phoneme>', 'delmarva', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (120, '3 O 1', '301', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (121, 'four  twenty two p em<break strength="none"/>', '422 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (122, 'feet', 'ft.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (123, 'north dakota', 'nd', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (124, 'minus ##', '-@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (125, 'four p em', '400 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (126, 'maryland', 'md', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (127, 'south', 's', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (128, '#:## ay em', '@@@ AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (129, 'four  twenty ay em<break strength="none"/>', '420 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (130, ' <phoneme alphabet="x-cmu" ph="  OW0 K IY0 CH OW1 B IY2">  </phoneme>', 'okeechobee', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (131, 'four  twenty two ay em<break strength="none"/>', '422 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (132, 'wednesday.', 'wed.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (133, ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 S T OW0 R M Z">  </phoneme>', 'thunderstorms', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (134, 'northwesterly', 'nwly', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (135, 'port a prince', 'port-au-prince', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (136, '## ## Z', '@@@@Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (137, 'u es highway 27', 'us-27', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (138, 'road', 'rd.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (139, 'one-quarter', '1/4', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (140, 'pennsylvania', 'pa', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (141, 'kilometers an hour', 'km hr', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (142, 'knots', 'kt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (143, ' <phoneme alphabet="x-cmu" ph=" K AA1 B OW0 S AA0 N L UW1 K AH0 Z ">  </phoneme>', 'cabo san lucas', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (144, 'july', 'jul', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (145, '17Z', '1700Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (146, ' <phoneme alphabet="x-cmu" ph="  AA0 N R IY1 ">  </phoneme>', 'henri', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (147, 'U S 41', 'u. s. 41', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (148, '3 0 5 2 2 9  4 5 2 2', '305-229-4522', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (149, 'saturday', 'sat', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (150, '09Z', '0900Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (151, 'cape cod <phoneme alphabet="x-cmu" ph=" ">  </phoneme>', 'cape cod', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (152, 'kilometers', 'km', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (153, 'knots.', 'kts.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (154, 'nine p em', '900 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (155, '00Z', '0000Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (156, 'february', 'feb', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (157, 'minus #', '-@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (158, '##:## p em', '@@@@ PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (159, 'millibars.', 'mb.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (160, 'august', 'aug', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (161, 'and', '&', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (162, 'tuesday', 'tueday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (163, 'june.', 'jun.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (164, '16Z', '1600Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (165, '23Z', '2300Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (166, 'three <break strength="none"/> ee ', 'three-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (167, 'midnight', '1200 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (168, 'plus #', '+@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (169, 'friday', 'fri', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (170, 'april', 'apr', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (171, 'feet', 'ft ', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (172, ' <phoneme alphabet="x-cmu" ph=" W IH1 N D ">  </phoneme>', 'wind', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (173, 'four  twelve p em<break strength="none"/>', '4:12 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (174, ' <phoneme alphabet="x-cmu" ph=" N IY0 R Z IY0 R OW0 ">  </phoneme>', 'near zero', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (175, 'friday', '.friday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (176, '5:00', '5:00 O CLOCK', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (177, '15Z', '1500Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (178, ' <phoneme alphabet="x-cmu" ph="  K IH1 Z EH0 M IY2">  </phoneme><break strength="none"/>', 'kissimmee', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (179, 'easterly', 'ely', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (180, 'four  twenty five p em<break strength="none"/>', '4:25 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (181, 'june ##', '(06/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (182, 'august.', 'aug.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (183, 'southerly', 'sly', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (184, 'for the rest of today', '.rest of today', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (185, 'georgia', 'ga', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (186, 'seven p em', '700 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (187, ' <phoneme alphabet="x-cmu" ph="  W IH1 N D S">  </phoneme><break strength="none"/>up', 'winds up', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (188, 'april ##', '(04/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (189, ' <phoneme alphabet="x-cmu" ph=" R AW1 T ">  </phoneme>', 'route', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (190, 'eighties', '80s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (191, 'connecticut', 'ct', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (192, 'ohio', 'oh', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (193, '02 hundred UTC', '0200 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (194, ' <phoneme alphabet="x-cmu" ph=" S P R IH1 NG Z">  </phoneme>', 'spgs', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (195, 'eleven <break strength="none"/> ee ', 'eleven-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (196, '1 kilometer', '1 km.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (197, 'four  twenty four p em<break strength="none"/>', '424 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (198, 'national weather service', 'nws', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (199, 'westerly', 'wly', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (200, 'four  twenty five ay em<break strength="none"/>', '425 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (201, 'oshinno graphic', 'oceanographic', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (202, 'a d p', 'adp', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (203, 'wisconsin', 'wi', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (204, 'ten p em', '1000 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (205, 'october.', 'oct.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (206, 'wednesday', '.wednesday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (207, '1 knot.', '1 kt.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (208, 'eastern daylight time', 'edt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (209, 'atlantic standard time', 'ast', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (210, '3 0 5 2 2 9 4 5 2 8', '305-229-4528', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (211, 'june', 'jun', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (212, 'northwest', 'nw', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (213, 'this afternoon', '.this afternoon', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (214, 'I 5 95', 'I595', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (215, ' <phoneme alphabet="x-cmu" ph=" AE0 L B AH0 M AA0 R L ">  </phoneme>', 'albemarle', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (216, '07Z', '0700Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (217, '### miles', '@@ @MI', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (218, '21Z', '2100Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (219, ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 S T OW0 R M">  </phoneme>', 'thunderstorm', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (220, 'visibilities', 'vsbys', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (221, '08 hundred UTC', '0800 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (222, 'west virginia', 'wv', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (223, 'october', 'oct', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (224, 'port a prince', 'PORT AU PRINCE', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (225, ' <phoneme alphabet="x-cmu" ph=" OW0 D EH1 T ">  </phoneme>', 'odette', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (226, '1 62 point # # #', '162.@@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (227, 'moderate <break strength="medium"/> rainfall', 'moderate rainfall', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (228, 'new york', 'ny', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (229, 'kentucky', 'ky', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (230, '02Z', '0200Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (231, 'september', 'sep', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (232, 'nautical miles', 'nm...', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (233, ' <phoneme alphabet="x-cmu" ph="  T IY2 N Z">  </phoneme>', '10s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (234, 'pacific standard time', 'pst', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (235, 'fifties', '50s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (236, 'four  fifty fore p em<break strength="none"/>', '4:54 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (237, '3 0 5  2 2 9  4 5 2 8', '305.229.4528', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (238, '18Z', '1800Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (239, ' <phoneme alphabet="x-cmu" ph=" S AE1 N T AH0 F EY1">  </phoneme>', 'santa fe', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (240, 'seventies', '70s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (241, 'four  twenty ay em<break strength="none"/>', '4:20 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (242, 'sixties', '60s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (243, 'thunderstorm', 'tstm', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (244, ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 SH AW0 ER0 Z ">  </phoneme>', 'thundershowers', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (245, 'central daylight time', 'cdt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (246, '##:## ay em', '@@@@ AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (247, ' <phoneme alphabet="x-cmu" ph=" HH AH0 M EY1 N AH0 ">  </phoneme>', 'jimena', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (248, 'january ##', '(01/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (249, 'one degree below zero', '1b', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (250, '8:00', '8:00 O CLOCK', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (251, 'i 75', 'i-75', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (252, 'nautical miles', 'nmi', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (253, 'kilometer.', 'km.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (254, 'fau we', 'fowey ', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (255, 'february.', 'feb.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (256, '# degrees below zero', 'b@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (257, 'interstate 5 95', 'interstate 595', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (258, 'three ay em', '300 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (259, 'march ##', '(03/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (260, 'november', 'nov', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (261, 'visibility', 'vsby', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (262, '1 foot', '1 ft.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (263, 'four  twenty four p em<break strength="none"/>', '4:24 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (264, 'nautical miles.', 'nm.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (265, '1 nautical mile.', '1 nm.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (266, 'forties', '40s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (267, 'twelve <break strength="none"/> ee ', 'twelve-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (268, 'monday', 'mon', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (269, 'twenty <break strength="none"/> ee ', 'twenty-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (270, ' <phoneme alphabet="x-cmu" ph=" AE0 N T IH1 L IY0 S">  </phoneme>', 'antilles', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (271, 'day tona beach<break strength="none"/>', 'daytona beach', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (272, 'mountain daylight time', 'mdt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (273, 'december.', 'dec.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (274, '08Z', '0800Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (275, ' <phoneme alphabet="x-cmu" ph=" UW0 UW1 N OW0">  </phoneme>', 'uno', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (276, ' <phoneme alphabet="x-cmu" ph=" EY1 Z OW0 R Z ">  </phoneme>', 'azores', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (277, 'nine ay em', '900 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (278, 'I 95', 'I95', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (279, ' <phoneme alphabet="x-cmu" ph=" OW1 L AA2 F ">  </phoneme>', 'olaf', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (280, 'four  twenty three p em<break strength="none"/>', '423 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (281, '6:00', '6:00 O CLOCK', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (282, 'knots', 'kts', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (283, 'four  twenty four ay em<break strength="none"/>', '4:24 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (284, 'air <break strength="none"/> for', 'air for', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (285, 'U S 41', 'U.S. 41', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (286, 'middle eighties', 'middle eighties', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (287, 'and the extended forecast', '.and the extended forecast', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (288, 'fog <break strength="none"/>', 'fog', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (289, '3 0 5 2 2 9 4 5 2 2', '305 flc229 to 4522', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (290, ' <phoneme alphabet="x-cmu" ph="  B IH1 M IH0 N IY0">  </phoneme>', 'bimini', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (291, '1 knot', '1 kt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (292, 'i 95', 'i-95', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (293, 'kriek', 'creek', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (294, ' <phoneme alphabet="x-cmu" ph=" HH AY1 T S ">  </phoneme>', 'hgts', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (295, 'six <break strength="none"/> ee ', 'six-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (296, 'eastern standard time', 'est.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (297, 'north', 'n', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (298, '3 0 5 2 2 9 4 5 2 2', '305.229.4522', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (299, '1 nautical mile', '1 nm', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (300, ' <phoneme alphabet="x-cmu" ph=" M IH1 K ">  </phoneme>', 'mc', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (301, 'for the rest of today', '.for the rest of today', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (302, 'four  twenty nine p em<break strength="none"/>', '4:29 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (303, 'pacific daylight time', 'pdt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (304, 'four  twenty eight ay em<break strength="none"/>', '4:28 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (305, 'thirteen <break strength="none"/> ee ', 'thirteen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (306, ' <phoneme alphabet="x-cmu" ph=" T AH0 W AA1 N AH0 P EH0 K ">  </phoneme>', 'tehuantepec', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (307, 'west', 'w', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (308, '01Z', '0100Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (309, ' <phoneme alphabet="x-cmu" ph=" IH1 L IH0 N OY1">  </phoneme>', 'illinois', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (310, 'the eastward <break strength="none"/>', 'the eastward', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (311, '03Z', '0300Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (312, 'noon', '12:00 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (313, ' <phoneme alphabet="x-cmu" ph=" HH AY1 Z ">  </phoneme>', 'highs', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (314, 'inn <break strength="none"/> and around', 'in and around', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (315, 'river<break strength="none"/>edge', 'river edge', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (316, 'four  twenty three p em<break strength="none"/>', '4:23 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (317, 'midnight', '12:00 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (318, 'one ay em', '100 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (319, 'november ##', '(11/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (320, 'southwest', 'sw', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (321, 'four  twenty eight p em<break strength="none"/>', '4:28 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (322, 'today', '.today', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (323, ' <phoneme alphabet="x-cmu" ph=" HH EH0 N L OW2 P EH0 N">  </phoneme>', 'henlopen', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (324, 'four  twenty nine ay em<break strength="none"/>', '4:29 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (325, '## degrees below zero', '@@b', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (326, 'thunderstorms', 'tstms', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (327, 'Monday.', 'mon.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (328, 'eleven ay em', '1100 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (329, 'two p em', '200 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (330, 'for the rest of today', '.remainder of today', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (331, 'wednesday', 'wed', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (332, '07 hundred UTC', '0700 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (333, 'central standard time', 'cst', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (334, 'northeast', 'ne', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (335, 'i<break strength="none"/>e', 'i.e.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (336, 'three p em', '300 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (337, 'four  twenty two p em<break strength="none"/>', '4:22 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (338, 'tuesday', '.tuesday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (339, 'eight p em', '800 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (340, 'overnight', '.overnight', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (341, 'highway 8 80', 'highway 880', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (342, 'september ##', '(09/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (343, 'mississippi', 'ms', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (344, '# sixteenths', '@/16', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (345, '05 hundred UTC', '0500 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (346, '## miles', '@@ MI', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (347, 'five p em', '500 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (348, ' <phoneme alphabet="x-cmu" ph=" M AW1 N T ">  </phoneme>', 'mt', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (349, 'air force base', 'afb', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (350, 'five ay em', '500 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (351, 'massachusetts', 'ma', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (352, '# degrees below zero', '@b', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (353, 'michigan', 'mi', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (354, 'see u dad', 'ciudad', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (355, 'two ay em', '200 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (356, ' <phoneme alphabet="x-cmu" ph=" N UW0 F AH0 N D L AH2 N D ">  </phoneme>', 'newfoundland', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (357, 'atlantic', 'atlc', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (358, 'showers', 'southhowers', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (359, ' <phoneme alphabet="x-cmu" ph=" AO0 ">  </phoneme>', 'au', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (360, ' <phoneme alphabet="x-cmu" ph="  W IH1 N D">  </phoneme><break strength="none"/>up', 'wind up', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (361, 'tonight', '.tonight', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (362, 'temperture', 'temp', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (363, 'NATIONAL WEATHER SERVICE', 'NWS/TPC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (364, 'four  twenty nine p em<break strength="none"/>', '429 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (365, ' <phoneme alphabet="x-cmu" ph="  S AE1 N T AH0 F EY1">  </phoneme> <break strength="none"/> river', 'santa fe river', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (366, 'nineties', '90s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (367, 'miles an hour', 'mph', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (368, '19Z', '1900Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (369, ' <phoneme alphabet="x-cmu" ph=" N IY0 R Z IY0 R OW0 ">  </phoneme>', 'near-zero', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (370, 'one degree below zero', 'b1', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (371, '09 hundred UTC', '0900 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (372, 'guam', 'gu', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (373, 'cloudy', 'cldy', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (374, 'U S   27', 'u.s. 27', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (375, ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 SH AW0 ER0">  </phoneme>', 'thundershower', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (376, 'virginia', 'va', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (377, 'march.', 'mar.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (378, '14Z', '1400Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (379, '03 hundred UTC', '0300 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (380, 'tuesday.', 'tue.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (381, ' <phoneme alphabet="x-cmu" ph=" HH EY1 L">  </phoneme>', 'hail', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (382, 'nine <break strength="none"/> ee ', 'nine-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (383, ' <phoneme alphabet="x-cmu" ph=" K L AW1 D IY0 N EH2 S">  </phoneme>', 'cloudiness', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (384, 'four  twenty three ay em<break strength="none"/>', '4:23 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (385, 'january.', 'jan.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (386, 'rhode island', 'ri', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (387, 'new jersey', 'nj', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (388, 'one-third', '1/3', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (389, 'seven ay em', '700 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (390, ' <phoneme alphabet="x-cmu" ph=" JH UW1 N Y ER0 ">  </phoneme>', 'jr', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (391, ' <phoneme alphabet="x-cmu" ph=" IY0 G N AA1 S IY0 OW0 ">  </phoneme>', 'ignacio', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (392, 'four  twenty one p em<break strength="none"/>', '4:21 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (393, 'thirties', '30s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (394, 'new hampshire', 'nh', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (395, 'six ay em', '600 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (396, '1 kilometer', '1 km', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (397, 'north carolina', 'nc', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (398, '20Z', '2000Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (399, 'thursday', 'thu', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (400, 'saturday', '.saturday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (401, 'july ##', '(07/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (402, 'four  twenty p em<break strength="none"/>', '4:20 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (403, 'thursday', '.thursday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (404, 'september.', 'sep.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (405, 'university', 'univ', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (406, 'two-thirds', '2/3', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (407, 'seven <break strength="none"/> ee ', 'seven-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (408, '# tenths', '@/10', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (409, 'march', 'mar', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (410, 'february ##', '(02/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (411, ' <phoneme alphabet="x-cmu" ph=" F R EH2 D EH0 R IY1 K AH0">  </phoneme>', 'frederica', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (412, 'april.', 'apr.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (413, 'noon', '1200 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (414, 'area <break strength="none"/> early', 'area early', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (415, '12Z', '1200Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (416, ' <phoneme alphabet="x-cmu" ph=" M UW1 V M EH0 N ">  </phoneme> <break strength="none"/> toward', 'movement toward', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (417, ' <phoneme alphabet="x-cmu" ph="  T W UH2 N T T IY0 Z">  </phoneme>', '20s', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (418, 'effect <break strength="none"/> tonight', 'effect tonight', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (419, 'delaware', 'de', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (420, 'd c', 'd.c.', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (421, '13Z', '1300Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (422, 'nine  ten p em<break strength="none"/>', '9:10 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (423, 'i 75', 'I75', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (424, 'visibility', 'vsb', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (425, '1 foot', '1 ft', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (426, 'eight ay em', '800 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (427, '10Z', '1000Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (428, 'east', 'e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (429, 'one p em', '100 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (430, 'florida<break strength="x-weak"/>atlantic<break strength="x-weak"/>university', 'fau', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (431, 'sunday', '.sunday', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (432, 'one-sixteenth', '1/16', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (433, 'foggy  <phoneme alphabet="x-cmu" ph=" ">  </phoneme>', 'foggy', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (434, '##:##', '@@:@@ o clock', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (435, 'scattered', 'southcattered', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (436, 'six p em', '600 PM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (437, ' <phoneme alphabet="x-cmu" ph=" K R AH0 OY0 ">  </phoneme>', 'croix', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (438, 'may ##', '(05/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (439, 'missing', 'misg', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (440, 'four  twenty four ay em<break strength="none"/>', '424 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (441, 'one  oh eight ay em<break strength="none"/>', '1:08 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (442, 'south carolina', 'sc', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (443, '22Z', '2200Z', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (444, '01 hundred UTC', '0100 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (445, 'chaka la skee', 'chokoloskee', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (446, 'south dakota', 'sd', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (447, 'december ##', '(12/@@', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (448, 'one-tenth', '1/10', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (449, ' <phoneme alphabet="x-cmu" ph=" M AA1 D AH0 R IH0 T ">  </phoneme>', 'moderate', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (450, 'illinois', 'il', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (451, 'alabama', 'al', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (452, ' <phoneme alphabet="x-cmu" ph="  P AA0 HH OW1 K IY0">  </phoneme>', 'pahokee', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (453, 'mountain standard time', 'mst', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (454, 'four  twenty nine ay em<break strength="none"/>', '429 AM', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (455, ' <phoneme alphabet="x-cmu" ph=" AE2 T M AH0 S F  EH1 R IH0 K">  </phoneme>', 'atmospheric', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (456, 'southeasterly', 'sely', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (457, 'nineteen <break strength="none"/> ee ', 'nineteen-e', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (458, 'oh 4 hundred UTC', '0400 UTC', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (459, 'virgin islands', 'vi', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (460, '20 nautical miles coastal', '20 nmcoastal ', 'paul-nat');
INSERT INTO bmh.word (id, substitute, word, dictionary) VALUES (461, '3 0 5 2 2 9 4 5 2 3', '305.229.4523', 'paul-nat');
ALTER SEQUENCE word_seq RESTART WITH 462;
