/**
 * This software was developed and / or modified by Raytheon Company,
 * pursuant to Contract DG133W-05-CQ-1067 with the US Government.
 * 
 * U.S. EXPORT CONTROLLED TECHNICAL DATA
 * This software product contains export-restricted data whose
 * export/transfer/disclosure is restricted by U.S. law. Dissemination
 * to non-U.S. persons whether in the United States or abroad requires
 * an export license or other authorization.
 * 
 * Contractor Name:        Raytheon Company
 * Contractor Address:     6825 Pine Street, Suite 340
 *                         Mail Stop B8
 *                         Omaha, NE 68106
 *                         402.291.0100
 * 
 * See the AWIPS II Master Rights File ("Master Rights File.pdf") for
 * further licensing information.
 **/

/**
 * Imports the English National Dictionary into the database during initial database load.
 *
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Mar 19, 2015 4291       bkowal      Initial creation.
 * May 12, 2015 4248       rjpeter     Remove bmh schema.
 **/

INSERT INTO dictionary (name, language, "national") VALUES ('paul-nat', 'ENGLISH', true);

INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '24Z', '2400Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'u  s   4 41', 'u.s. 441', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'i 5 95', 'i-595', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '#:##', '#:## o clock', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" JH AA0 N S AH0 N V IH0 L">  </phoneme>', 'johnsonville', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'saturday.', 'sat.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'alaska daylight time', 'adt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'august ##', '(08/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'this afternoon', '.day one...this afternoon.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty five p em<break strength="none"/>', '425 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" F R AY1 D EY2 ">  </phoneme>', 'friday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'point', 'pt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'knots.', 'kt.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" K AE2 R EH0 B IY1 AH0 N ">  </phoneme>', 'caribbean', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  IH1 Z AH0 D OW0 R ">  </phoneme>', 'isidore', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'plus ##', '+##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'u s   1', 'u.s. 1', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'cam peachy', 'campeche', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'ten ay em', '1000 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'king junior', 'king jr', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '04Z', '0400Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'minnesota', 'mn', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'fifteen <break strength="none"/> ee ', 'fifteen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'december', 'dec', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tammy ammy', 'tamiami', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty p em<break strength="none"/>', '420 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'florida', 'fl', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'january', 'jan', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four ay em', '400 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty three ay em<break strength="none"/>', '423 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'u  s 98', 'u.s. 98', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'november.', 'nov.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'the nex 24 hours', 'the next 24 hours', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" F AH0 L IY1 SH AH0 ">  </phoneme>', 'felicia', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '20 nautical miles to', '20 nmto', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one-eighth', '1/8', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'southwesterly', 'swly', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'sixteen <break strength="none"/> ee ', 'sixteen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thursday.', 'thu.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '7:00', '7:00 O CLOCK', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  S">  </phoneme>', '''s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'fourteen<break strength="none"/> ee ', 'fourteen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'and now the extended forecast', '.and now the extended forecast', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'seventeen <break strength="none"/> ee ', 'seventeen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '00 hunderd UTC', '0000 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" R EH1 Z ER0 V OW0 R ">  </phoneme>', 'reservoir', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'pacific', 'pac', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5 2 2 9 4 5 2 3', '305-229-4523', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one <break strength="none"/> ee ', 'one-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" D AA1 AO1 N ">  </phoneme>', 'dawn', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nine  ten p em<break strength="none"/>', '910 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eighteen <break strength="none"/> ee ', 'eighteen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'national weather service', 'NWS TPC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'road', 'rd', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'two  fifty two ay em<break strength="none"/>', '2:52 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'five <break strength="none"/> ee ', 'five-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'for the rest of today', '.for the remainder of today', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one-half', '1/2', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'monday', '.monday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'july', 'jul.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  N EH1 K S R AE2  D">  </phoneme>', 'nexrad', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'slew', 'slough', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twelve p em<break strength="none"/>', '412 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'noah', 'noaa', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '##.##  feet', '##.## feet', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty two ay em<break strength="none"/>', '4:22 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty five ay em<break strength="none"/>', '4:25 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" M IH1 N ER0 AH0 L ">  </phoneme>', 'mineral', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'millibars', 'mb', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'choppy too  rough', 'choppy to rough', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eleven p em', '1100 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty one ay em<break strength="none"/>', '421 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'kilometers an hour', 'km/hr', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tennessee', 'tn', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '11Z', '1100Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'today', '.day one...today.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '06Z', '0600Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'scattered <break strength="none"/> frost', 'scattered frost', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" EY1 S AH0 AA0 S ">  </phoneme>', 'asos', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '## degrees below zero', 'b##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eastern standard time', 'est', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four <break strength="none"/> ee ', 'four-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 mile an hour', '1 mph', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty eight ay em<break strength="none"/>', '428 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty one ay em<break strength="none"/>', '4:21 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one <break strength="none"/> oh eight ay em', '108 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '10 hundred UTC', '1000 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'october ##', '(10/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nautical miles', 'nm', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '# miles', '# MI', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'northeasterly', 'nely', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'southeast', 'se', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty eight p em<break strength="none"/>', '428 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'friday.', 'fri.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'northerly', 'nly', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'sunny', 'southunny', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '# eighths', '#/8', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" EH1 R P OW0 R T ">  </phoneme>', 'arpt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'd c', 'dc', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'maine', 'me', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" AE0 T L AE0 N T IH2 K ">  </phoneme>', 'atlantic', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'vermont', 'vt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '05Z', '0500Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'three-quarters', '3/4', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'U S   27', 'U.S.  27', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eight <break strength="none"/> ee ', 'eight-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'ten <break strength="none"/> ee ', 'ten-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" F EH1 N W IH0 K K">  </phoneme>', 'fenwick', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'two <break strength="none"/> ee ', 'two-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'puerto rico', 'pr', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty one p em<break strength="none"/>', '421 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '06 hundred UTC', '0600 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" S IY0 EY0 G OW0    D  EY0">  </phoneme><break strength="none"/> <phoneme alphabet="x-cmu" ph="  AA0 V IY1 L AA0">  </phoneme>', 'CIEGO DE AVILA', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" K R AO1 S R OW0 D Z ">  </phoneme>', 'xrds', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tuesday', 'tue', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '#:## p em', '### PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" AA0 N R IY1 K EY0 ">  </phoneme>', 'enrique', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'per reihn', 'Perrine', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" D EH0 L M AA1 R V AH0 ">  </phoneme>', 'delmarva', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 O 1', '301', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty two p em<break strength="none"/>', '422 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'feet', 'ft.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'north dakota', 'nd', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'minus ##', '-##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four p em', '400 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'maryland', 'md', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'south', 's', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '#:## ay em', '### AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty ay em<break strength="none"/>', '420 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  OW0 K IY0 CH OW1 B IY2">  </phoneme>', 'okeechobee', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty two ay em<break strength="none"/>', '422 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'wednesday.', 'wed.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 S T OW0 R M Z">  </phoneme>', 'thunderstorms', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'northwesterly', 'nwly', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'port a prince', 'port-au-prince', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '## ## Z', '###Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'u es highway 27', 'us-27', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'road', 'rd.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one-quarter', '1/4', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'pennsylvania', 'pa', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'kilometers an hour', 'km hr', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'knots', 'kt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" K AA1 B OW0 S AA0 N L UW1 K AH0 Z ">  </phoneme>', 'cabo san lucas', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'july', 'jul', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '17Z', '1700Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  AA0 N R IY1 ">  </phoneme>', 'henri', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'U S 41', 'u. s. 41', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5 2 2 9  4 5 2 2', '305-229-4522', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'saturday', 'sat', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '09Z', '0900Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'cape cod <phoneme alphabet="x-cmu" ph=" ">  </phoneme>', 'cape cod', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'kilometers', 'km', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'knots.', 'kts.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nine p em', '900 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '00Z', '0000Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'february', 'feb', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'minus #', '-#', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '##:## p em', '#### PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'millibars.', 'mb.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'august', 'aug', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'and', '&', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tuesday', 'tueday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'june.', 'jun.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '16Z', '1600Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '23Z', '2300Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'three <break strength="none"/> ee ', 'three-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'midnight', '1200 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'plus #', '+#', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'friday', 'fri', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'april', 'apr', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'feet', 'ft ', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twelve p em<break strength="none"/>', '4:12 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" N IY0 R Z IY0 R OW0 ">  </phoneme>', 'near zero', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'friday', '.friday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '5:00', '5:00 O CLOCK', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '15Z', '1500Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  K IH1 Z EH0 M IY2">  </phoneme><break strength="none"/>', 'kissimmee', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'easterly', 'ely', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty five p em<break strength="none"/>', '4:25 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'june ##', '(06/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'august.', 'aug.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'southerly', 'sly', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'for the rest of today', '.rest of today', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'georgia', 'ga', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'seven p em', '700 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'april ##', '(04/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" R AW1 T ">  </phoneme>', 'route', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eighties', '80s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'connecticut', 'ct', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'ohio', 'oh', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '02 hundred UTC', '0200 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" S P R IH1 NG Z">  </phoneme>', 'spgs', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eleven <break strength="none"/> ee ', 'eleven-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 kilometer', '1 km.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty four p em<break strength="none"/>', '424 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'national weather service', 'nws', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'westerly', 'wly', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty five ay em<break strength="none"/>', '425 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'oshinno graphic', 'oceanographic', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'a d p', 'adp', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'wisconsin', 'wi', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'ten p em', '1000 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'october.', 'oct.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'wednesday', '.wednesday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 knot.', '1 kt.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eastern daylight time', 'edt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'atlantic standard time', 'ast', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5 2 2 9 4 5 2 8', '305-229-4528', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'june', 'jun', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'northwest', 'nw', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'this afternoon', '.this afternoon', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'I 5 95', 'I595', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" AE0 L B AH0 M AA0 R L ">  </phoneme>', 'albemarle', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '07Z', '0700Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '### miles', '## #MI', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '21Z', '2100Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 S T OW0 R M">  </phoneme>', 'thunderstorm', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'visibilities', 'vsbys', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '08 hundred UTC', '0800 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'west virginia', 'wv', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'october', 'oct', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'port a prince', 'PORT AU PRINCE', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" OW0 D EH1 T ">  </phoneme>', 'odette', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 62 point # # #', '162.###', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'moderate <break strength="medium"/> rainfall', 'moderate rainfall', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'new york', 'ny', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'kentucky', 'ky', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '02Z', '0200Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'september', 'sep', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nautical miles', 'nm...', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  T IY2 N Z">  </phoneme>', '10s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'pacific standard time', 'pst', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'fifties', '50s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  fifty fore p em<break strength="none"/>', '4:54 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5  2 2 9  4 5 2 8', '305.229.4528', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '18Z', '1800Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" S AE1 N T AH0 F EY1">  </phoneme>', 'santa fe', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'seventies', '70s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty ay em<break strength="none"/>', '4:20 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'sixties', '60s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thunderstorm', 'tstm', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 SH AW0 ER0 Z ">  </phoneme>', 'thundershowers', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'central daylight time', 'cdt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '##:## ay em', '#### AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" HH AH0 M EY1 N AH0 ">  </phoneme>', 'jimena', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'january ##', '(01/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one degree below zero', '1b', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '8:00', '8:00 O CLOCK', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'i 75', 'i-75', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nautical miles', 'nmi', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'kilometer.', 'km.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'fau we', 'fowey ', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'february.', 'feb.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '# degrees below zero', 'b#', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'interstate 5 95', 'interstate 595', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'three ay em', '300 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'march ##', '(03/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'november', 'nov', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'visibility', 'vsby', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 foot', '1 ft.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty four p em<break strength="none"/>', '4:24 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nautical miles.', 'nm.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 nautical mile.', '1 nm.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'forties', '40s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'twelve <break strength="none"/> ee ', 'twelve-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'monday', 'mon', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'twenty <break strength="none"/> ee ', 'twenty-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" AE0 N T IH1 L IY0 S">  </phoneme>', 'antilles', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'day tona beach<break strength="none"/>', 'daytona beach', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'mountain daylight time', 'mdt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'december.', 'dec.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '08Z', '0800Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" UW0 UW1 N OW0">  </phoneme>', 'uno', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" EY1 Z OW0 R Z ">  </phoneme>', 'azores', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nine ay em', '900 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'I 95', 'I95', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" OW1 L AA2 F ">  </phoneme>', 'olaf', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty three p em<break strength="none"/>', '423 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '6:00', '6:00 O CLOCK', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'knots', 'kts', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty four ay em<break strength="none"/>', '4:24 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'air <break strength="none"/> for', 'air for', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'U S 41', 'U.S. 41', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'middle eighties', 'middle eighties', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'and the extended forecast', '.and the extended forecast', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'fog <break strength="none"/>', 'fog', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5 2 2 9 4 5 2 2', '305 flc229 to 4522', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  B IH1 M IH0 N IY0">  </phoneme>', 'bimini', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 knot', '1 kt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'i 95', 'i-95', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'kriek', 'creek', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" HH AY1 T S ">  </phoneme>', 'hgts', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'six <break strength="none"/> ee ', 'six-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eastern standard time', 'est.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'north', 'n', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5 2 2 9 4 5 2 2', '305.229.4522', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 nautical mile', '1 nm', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" M IH1 K ">  </phoneme>', 'mc', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'for the rest of today', '.for the rest of today', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty nine p em<break strength="none"/>', '4:29 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'pacific daylight time', 'pdt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty eight ay em<break strength="none"/>', '4:28 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thirteen <break strength="none"/> ee ', 'thirteen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" T AH0 W AA1 N AH0 P EH0 K ">  </phoneme>', 'tehuantepec', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'west', 'w', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '01Z', '0100Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" IH1 L IH0 N OY1">  </phoneme>', 'illinois', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'the eastward <break strength="none"/>', 'the eastward', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '03Z', '0300Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'noon', '12:00 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" HH AY1 Z ">  </phoneme>', 'highs', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'inn <break strength="none"/> and around', 'in and around', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'river<break strength="none"/>edge', 'river edge', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty three p em<break strength="none"/>', '4:23 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'midnight', '12:00 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one ay em', '100 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'november ##', '(11/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'southwest', 'sw', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty eight p em<break strength="none"/>', '4:28 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'today', '.today', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" HH EH0 N L OW2 P EH0 N">  </phoneme>', 'henlopen', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty nine ay em<break strength="none"/>', '4:29 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '## degrees below zero', '##b', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thunderstorms', 'tstms', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'Monday.', 'mon.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eleven ay em', '1100 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'two p em', '200 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'for the rest of today', '.remainder of today', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'wednesday', 'wed', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '07 hundred UTC', '0700 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'central standard time', 'cst', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'northeast', 'ne', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'i<break strength="none"/>e', 'i.e.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'three p em', '300 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty two p em<break strength="none"/>', '4:22 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tuesday', '.tuesday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eight p em', '800 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'overnight', '.overnight', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'highway 8 80', 'highway 880', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'september ##', '(09/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'mississippi', 'ms', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '# sixteenths', '#/16', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '05 hundred UTC', '0500 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '## miles', '## MI', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'five p em', '500 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" M AW1 N T ">  </phoneme>', 'mt', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'air force base', 'afb', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'five ay em', '500 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'massachusetts', 'ma', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '# degrees below zero', '#b', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'michigan', 'mi', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'see u dad', 'ciudad', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'two ay em', '200 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" N UW0 F AH0 N D L AH2 N D ">  </phoneme>', 'newfoundland', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'atlantic', 'atlc', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'showers', 'southhowers', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" AO0 ">  </phoneme>', 'au', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tonight', '.tonight', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'temperture', 'temp', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'NATIONAL WEATHER SERVICE', 'NWS/TPC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty nine p em<break strength="none"/>', '429 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  S AE1 N T AH0 F EY1">  </phoneme> <break strength="none"/> river', 'santa fe river', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nineties', '90s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'miles an hour', 'mph', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '19Z', '1900Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" N IY0 R Z IY0 R OW0 ">  </phoneme>', 'near-zero', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one degree below zero', 'b1', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '09 hundred UTC', '0900 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'guam', 'gu', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'cloudy', 'cldy', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'U S   27', 'u.s. 27', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  TH AH1 N D ER0 SH AW0 ER0">  </phoneme>', 'thundershower', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'virginia', 'va', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'march.', 'mar.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '14Z', '1400Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '03 hundred UTC', '0300 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'tuesday.', 'tue.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" HH EY1 L">  </phoneme>', 'hail', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nine <break strength="none"/> ee ', 'nine-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" K L AW1 D IY0 N EH2 S">  </phoneme>', 'cloudiness', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty three ay em<break strength="none"/>', '4:23 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'january.', 'jan.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'rhode island', 'ri', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'new jersey', 'nj', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one-third', '1/3', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'seven ay em', '700 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" JH UW1 N Y ER0 ">  </phoneme>', 'jr', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" IY0 G N AA1 S IY0 OW0 ">  </phoneme>', 'ignacio', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty one p em<break strength="none"/>', '4:21 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thirties', '30s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'new hampshire', 'nh', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'six ay em', '600 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 kilometer', '1 km', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'north carolina', 'nc', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '20Z', '2000Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thursday', 'thu', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'saturday', '.saturday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'july ##', '(07/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty p em<break strength="none"/>', '4:20 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'thursday', '.thursday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'september.', 'sep.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'university', 'univ', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'two-thirds', '2/3', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'seven <break strength="none"/> ee ', 'seven-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '# tenths', '#/10', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'march', 'mar', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'february ##', '(02/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" F R EH2 D EH0 R IY1 K AH0">  </phoneme>', 'frederica', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'april.', 'apr.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'noon', '1200 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'area <break strength="none"/> early', 'area early', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '12Z', '1200Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" M UW1 V M EH0 N ">  </phoneme> <break strength="none"/> toward', 'movement toward', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  T W UH2 N T T IY0 Z">  </phoneme>', '20s', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'effect <break strength="none"/> tonight', 'effect tonight', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'delaware', 'de', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'd c', 'd.c.', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '13Z', '1300Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nine  ten p em<break strength="none"/>', '9:10 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'i 75', 'I75', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'visibility', 'vsb', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '1 foot', '1 ft', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'eight ay em', '800 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '10Z', '1000Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'east', 'e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one p em', '100 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'florida<break strength="x-weak"/>atlantic<break strength="x-weak"/>university', 'fau', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'sunday', '.sunday', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one-sixteenth', '1/16', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'foggy  <phoneme alphabet="x-cmu" ph=" ">  </phoneme>', 'foggy', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '##:##', '##:## o clock', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'scattered', 'southcattered', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'six p em', '600 PM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" K R AH0 OY0 ">  </phoneme>', 'croix', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'may ##', '(05/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'missing', 'misg', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty four ay em<break strength="none"/>', '424 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one  oh eight ay em<break strength="none"/>', '1:08 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'south carolina', 'sc', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '22Z', '2200Z', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '01 hundred UTC', '0100 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'chaka la skee', 'chokoloskee', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'south dakota', 'sd', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'december ##', '(12/##', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'one-tenth', '1/10', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" M AA1 D AH0 R IH0 T ">  </phoneme>', 'moderate', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'illinois', 'il', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'alabama', 'al', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  P AA0 HH OW1 K IY0">  </phoneme>', 'pahokee', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'mountain standard time', 'mst', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'four  twenty nine ay em<break strength="none"/>', '429 AM', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" AE2 T M AH0 S F  EH1 R IH0 K">  </phoneme>', 'atmospheric', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'southeasterly', 'sely', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'nineteen <break strength="none"/> ee ', 'nineteen-e', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'oh 4 hundred UTC', '0400 UTC', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'virgin islands', 'vi', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '20 nautical miles coastal', '20 nmcoastal ', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), '3 0 5 2 2 9 4 5 2 3', '305.229.4523', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" W IH1 N D ">  </phoneme>', 'wind', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" W IH1 N D S ">  </phoneme>', 'winds', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W AY2 N D ">  </phoneme><break strength="none"/>up', 'wind up', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W IH1 N D ">  </phoneme><break strength="none"/>up to', 'wind up to', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W AY2 N D S ">  </phoneme><break strength="none"/>up', 'winds up', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W IH1 N D S ">  </phoneme><break strength="none"/>up to', 'winds up to', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W AY2 N D ">  </phoneme><break strength="none"/>down', 'wind down', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W IH1 N D ">  </phoneme><break strength="none"/>down to', 'wind down to', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W AY2 N D S ">  </phoneme><break strength="none"/>down', 'winds down', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph="  W IH1 N D S ">  </phoneme><break strength="none"/>down to', 'winds down to', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), ' <phoneme alphabet="x-cmu" ph=" L IY1 D ">  </phoneme>', 'lead', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'rek erd', 'record', 'paul-nat');
INSERT INTO word (id, substitute, word, dictionary) VALUES (nextval('word_seq'), 'o bjects', 'objects', 'paul-nat');
ALTER SEQUENCE word_seq RESTART WITH 466;
