//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:58:15 PM CDT 
//

/**
 * JAXB representation of the SSML break tag.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Jun 12, 2014 3259       bkowal      Initial creation
 * 
 * </pre>
 * 
 * @author bkowal
 * @version 1.0
 */

package com.raytheon.uf.common.bmh.schemas.ssml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for break complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="break">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="time" type="{http://www.w3.org/2001/10/synthesis}duration" />
 *       &lt;attribute name="strength" type="{http://www.w3.org/2001/10/synthesis}strength.datatype" default="medium" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = Break.NAME)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = Break.NAME)
public class Break implements Serializable {

    public static final String NAME = "break";
    
    private static final long serialVersionUID = 4474420461547579698L;

    @XmlAttribute(name = "time")
    protected String time;

    @XmlAttribute(name = "strength")
    protected StrengthDatatype strength;

    /**
     * Gets the value of the time property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return possible object is {@link StrengthDatatype }
     * 
     */
    public StrengthDatatype getStrength() {
        if (strength == null) {
            return StrengthDatatype.MEDIUM;
        } else {
            return strength;
        }
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *            allowed object is {@link StrengthDatatype }
     * 
     */
    public void setStrength(StrengthDatatype value) {
        this.strength = value;
    }

}
