//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:58:15 PM CDT 
//

package com.raytheon.uf.common.bmh.schemas.ssml;

/**
 * JAXB representation of the SSML audio tag.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Jun 12, 2014 3259       bkowal      Initial creation
 * 
 * </pre>
 * 
 * @author bkowal
 * @version 1.0
 */

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for audio complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="audio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/2001/10/synthesis}descAndSentenceAndStructure.class"/>
 *       &lt;attribute name="src" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content" })
@XmlSeeAlso({ Audio.class })
public class OriginalAudio implements Serializable {

    private static final long serialVersionUID = 4155961009177284924L;

    @XmlElementRefs({
            @XmlElementRef(name = "aws", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "desc", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "struct", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false) })
    @XmlMixed
    protected List<Serializable> content;

    @XmlAttribute(name = "src")
    @XmlSchemaType(name = "anyURI")
    protected String src;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Audio }{@code >} {@link JAXBElement }
     * {@code <}{@link Desc }{@code >} {@link JAXBElement }{@code <}{@link Voice }
     * {@code >} {@link JAXBElement }{@code <}{@link Phoneme }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >} {@link JAXBElement }
     * {@code <}{@link Emphasis }{@code >} {@link JAXBElement }{@code <}
     * {@link Sub }{@code >} {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link String } {@link JAXBElement }{@code <}{@link Prosody }{@code >}
     * {@link JAXBElement }{@code <}{@link Sentence }{@code >} {@link JAXBElement }
     * {@code <}{@link Paragraph }{@code >} {@link JAXBElement }{@code <}
     * {@link SayAs }{@code >} {@link JAXBElement }{@code <}{@link Mark }{@code >}
     * {@link JAXBElement }{@code <}{@link Break }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setSrc(String value) {
        this.src = value;
    }

}
