//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:58:15 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2001/10/synthesis", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.raytheon.uf.common.bmh.schemas.ssml;
