//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:58:15 PM CDT 
//

/**
 * JAXB representation of the SSML prosody tag.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Jun 12, 2014 3259       bkowal      Initial creation
 * 
 * </pre>
 * 
 * @author bkowal
 * @version 1.0
 */

package com.raytheon.uf.common.bmh.schemas.ssml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for prosody complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="prosody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/2001/10/synthesis}sentenceAndStructure.class"/>
 *       &lt;attribute name="pitch" type="{http://www.w3.org/2001/10/synthesis}pitch.datatype" />
 *       &lt;attribute name="contour" type="{http://www.w3.org/2001/10/synthesis}contour.datatype" />
 *       &lt;attribute name="range" type="{http://www.w3.org/2001/10/synthesis}range.datatype" />
 *       &lt;attribute name="rate" type="{http://www.w3.org/2001/10/synthesis}rate.datatype" />
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/10/synthesis}duration" />
 *       &lt;attribute name="volume" type="{http://www.w3.org/2001/10/synthesis}volume.datatype" default="100.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = Prosody.NAME)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = Prosody.NAME, propOrder = { "content" })
public class Prosody implements Serializable {

    public static final String NAME = "prosody";

    private static final long serialVersionUID = -2905241844541633465L;

    @XmlElementRefs({
            @XmlElementRef(name = "aws", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "struct", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false) })
    @XmlMixed
    protected List<Serializable> content;

    @XmlAttribute(name = "pitch")
    protected String pitch;

    @XmlAttribute(name = "contour")
    protected List<String> contour;

    @XmlAttribute(name = "range")
    protected String range;

    @XmlAttribute(name = "rate")
    protected String rate;

    @XmlAttribute(name = "duration")
    protected String duration;

    @XmlAttribute(name = "volume")
    protected String volume;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Audio }{@code >} {@link JAXBElement }
     * {@code <}{@link Voice }{@code >} {@link JAXBElement }{@code <}
     * {@link Phoneme }{@code >} {@link JAXBElement }{@code <}{@link Object }
     * {@code >} {@link JAXBElement }{@code <}{@link Emphasis }{@code >}
     * {@link JAXBElement }{@code <}{@link Sub }{@code >} {@link JAXBElement }
     * {@code <}{@link Object }{@code >} {@link String } {@link JAXBElement }
     * {@code <}{@link Prosody }{@code >} {@link JAXBElement }{@code <}
     * {@link Sentence }{@code >} {@link JAXBElement }{@code <}{@link SayAs }
     * {@code >} {@link JAXBElement }{@code <}{@link Mark }{@code >}
     * {@link JAXBElement }{@code <}{@link Paragraph }{@code >}
     * {@link JAXBElement }{@code <}{@link Break }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the pitch property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPitch() {
        return pitch;
    }

    /**
     * Sets the value of the pitch property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPitch(String value) {
        this.pitch = value;
    }

    /**
     * Gets the value of the contour property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the contour property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContour().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getContour() {
        if (contour == null) {
            contour = new ArrayList<String>();
        }
        return this.contour;
    }

    /**
     * Gets the value of the range property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRange() {
        return range;
    }

    /**
     * Sets the value of the range property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRange(String value) {
        this.range = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRate(String value) {
        this.rate = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVolume() {
        if (volume == null) {
            return "100";
        } else {
            return volume;
        }
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setVolume(String value) {
        this.volume = value;
    }

}
