//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:58:15 PM CDT 
//

/**
 * JAXB representation of the SSML voice tag.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Jun 12, 2014 3259       bkowal      Initial creation
 * 
 * </pre>
 * 
 * @author bkowal
 * @version 1.0
 */

package com.raytheon.uf.common.bmh.schemas.ssml;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for voice complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="voice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.w3.org/2001/10/synthesis}sentenceAndStructure.class"/>
 *       &lt;attribute name="gender" type="{http://www.w3.org/2001/10/synthesis}gender.datatype" />
 *       &lt;attribute name="age" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="variant" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/10/synthesis}voicenames.datatype" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = Voice.NAME)
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = Voice.NAME, propOrder = { "content" })
public class Voice implements Serializable {

    public static final String NAME = "voice";

    private static final long serialVersionUID = -2284886698395930014L;

    @XmlElementRefs({
            @XmlElementRef(name = "aws", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "struct", namespace = "http://www.w3.org/2001/10/synthesis", type = JAXBElement.class, required = false) })
    @XmlMixed
    protected List<Serializable> content;

    @XmlAttribute(name = "gender")
    protected GenderDatatype gender;

    @XmlAttribute(name = "age")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger age;

    @XmlAttribute(name = "variant")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger variant;

    @XmlAttribute(name = "name")
    protected List<String> name;

    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Audio }{@code >} {@link JAXBElement }
     * {@code <}{@link Voice }{@code >} {@link JAXBElement }{@code <}
     * {@link Phoneme }{@code >} {@link JAXBElement }{@code <}{@link Object }
     * {@code >} {@link JAXBElement }{@code <}{@link Emphasis }{@code >}
     * {@link JAXBElement }{@code <}{@link Sub }{@code >} {@link JAXBElement }
     * {@code <}{@link Object }{@code >} {@link String } {@link JAXBElement }
     * {@code <}{@link Prosody }{@code >} {@link JAXBElement }{@code <}
     * {@link Sentence }{@code >} {@link JAXBElement }{@code <}{@link SayAs }
     * {@code >} {@link JAXBElement }{@code <}{@link Mark }{@code >}
     * {@link JAXBElement }{@code <}{@link Paragraph }{@code >}
     * {@link JAXBElement }{@code <}{@link Break }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return possible object is {@link GenderDatatype }
     * 
     */
    public GenderDatatype getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *            allowed object is {@link GenderDatatype }
     * 
     */
    public void setGender(GenderDatatype value) {
        this.gender = value;
    }

    /**
     * Gets the value of the age property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setAge(BigInteger value) {
        this.age = value;
    }

    /**
     * Gets the value of the variant property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getVariant() {
        return variant;
    }

    /**
     * Sets the value of the variant property.
     * 
     * @param value
     *            allowed object is {@link BigInteger }
     * 
     */
    public void setVariant(BigInteger value) {
        this.variant = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getName() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
