//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 12:58:15 PM CDT 
//

/**
 * JAXB representation of volume.scale.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Jun 12, 2014 3259       bkowal      Initial creation
 * 
 * </pre>
 * 
 * @author bkowal
 * @version 1.0
 */

package com.raytheon.uf.common.bmh.schemas.ssml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for volume.scale.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="volume.scale">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="silent"/>
 *     &lt;enumeration value="x-soft"/>
 *     &lt;enumeration value="soft"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="loud"/>
 *     &lt;enumeration value="x-loud"/>
 *     &lt;enumeration value="default"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "volume.scale")
@XmlEnum
public enum VolumeScale {

    @XmlEnumValue("silent")
    SILENT("silent"),
    @XmlEnumValue("x-soft")
    X_SOFT("x-soft"),
    @XmlEnumValue("soft")
    SOFT("soft"),
    @XmlEnumValue("medium")
    MEDIUM("medium"),
    @XmlEnumValue("loud")
    LOUD("loud"),
    @XmlEnumValue("x-loud")
    X_LOUD("x-loud"),
    @XmlEnumValue("default")
    DEFAULT("default");
    private final String value;

    VolumeScale(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VolumeScale fromValue(String v) {
        for (VolumeScale c: VolumeScale.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
