/**
 * This software was developed and / or modified by Raytheon Company,
 * pursuant to Contract DG133W-05-CQ-1067 with the US Government.
 * 
 * U.S. EXPORT CONTROLLED TECHNICAL DATA
 * This software product contains export-restricted data whose
 * export/transfer/disclosure is restricted by U.S. law. Dissemination
 * to non-U.S. persons whether in the United States or abroad requires
 * an export license or other authorization.
 * 
 * Contractor Name:        Raytheon Company
 * Contractor Address:     6825 Pine Street, Suite 340
 *                         Mail Stop B8
 *                         Omaha, NE 68106
 *                         402.291.0100
 * 
 * See the AWIPS II Master Rights File ("Master Rights File.pdf") for
 * further licensing information.
 **/
package com.raytheon.uf.common.bmh.request;

import java.util.List;

import com.raytheon.uf.common.bmh.datamodel.transmitter.LdadConfig;
import com.raytheon.uf.common.serialization.annotations.DynamicSerialize;
import com.raytheon.uf.common.serialization.annotations.DynamicSerializeElement;

/**
 * Response object generated by the {@link LdadConfigHandler}. Contains
 * references to the {@link LdadConfig} records that have been retrieved or
 * saved.
 * 
 * <pre>
 * 
 * SOFTWARE HISTORY
 * 
 * Date         Ticket#    Engineer    Description
 * ------------ ---------- ----------- --------------------------
 * Nov 11, 2014 3803       bkowal      Initial creation
 * 
 * </pre>
 * 
 * @author bkowal
 * @version 1.0
 */
@DynamicSerialize
public class LdadConfigResponse {

    @DynamicSerializeElement
    private List<LdadConfig> ldadConfigurations;

    /**
     * 
     */
    public LdadConfigResponse() {
    }

    /**
     * @return the ldadConfigurations
     */
    public List<LdadConfig> getLdadConfigurations() {
        return ldadConfigurations;
    }

    /**
     * @param ldadConfigurations
     *            the ldadConfigurations to set
     */
    public void setLdadConfigurations(List<LdadConfig> ldadConfigurations) {
        this.ldadConfigurations = ldadConfigurations;
    }
}